In [1]:
############# Introduction to Numpy #############
#The simplest operation in Numpy, is to create an array from a list.
#Arrays works better with maths methods. Lists only works with strings operations

# Import the numpy package as np
import numpy as np

# Create LIST OF baseball height of some baseball players in centimeters.
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
print(baseball)
# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))
print(np_baseball)

[180, 215, 210, 210, 188, 176, 209, 200]
<class 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]


In [13]:
# height is available as a regular list

# Import numpy
import numpy as np

height_in = [74,74,72,75,75,73]

weight_lb = [205, 190, 180, 205, 190, 195]

# Create a numpy array from height_in LIST: np_height_in
np_height_in = np.array(height_in)

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

# Calculate the BMI: bmi
np_bmi = np_weight_kg/(np_height_m ** 2)

# Print out bmi
print("bmi =  " ,np_bmi)


[74 74 72 75 75 73]
[1.8796 1.8796 1.8288 1.905  1.905  1.8542]
bmi =   [26.32015089 24.39428619 24.41211827 25.62295933 23.74810865 25.72686361]


In [14]:
#Numpy is great for doing vector arithmetic. 
#If you compare its functionality with regular Python lists, however, some things have changed.
#First of all, numpy arrays cannot contain elements with different types. 
#If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.3
#Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

#Have a look at this line of code:

np.array([True, 1, 2]) + np.array([3, 4, False])


array([4, 5, 2])

In [19]:
import numpy as np

height_in = [74,74,72,75,75,73,80,50,70,83]

np_height_in = np.array(height_in)


# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out the weight at index 4
print(np_height_in[4])

# Print out sub-array of np_height_in: index 5 up to and including index 8
print(np_height_in[5:8])

75
[73 80 50]


In [1]:
# 2D NumPy Arrays - Lists of List
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

# Print out the 4rd row of np_baseball
print(np_baseball[3,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 2nd player
print(np_baseball[2,0])

conversion = np.array([0.0254 , 0.453592])

print(np_baseball * conversion)

# Print out the mean of np_height_in
print(np_baseball.mean())

# Print out the median of np_height_in
print(np.median(np_baseball))



<class 'numpy.ndarray'>
(4, 2)
[188.   75.2]
210.0
[[ 4.572     35.5616128]
 [ 5.461     46.5838984]
 [ 5.334     44.678812 ]
 [ 4.7752    34.1101184]]
143.475
141.35


In [3]:
#Selecting NumPy Subsetings

# Print out the 2nd ROW of np_baseball
print(np_baseball[1,:])

# Select the entire 2nd COLUMN of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]
print(np_weight_lb)


# Print out height of 4th player
print(np_baseball[3,0])

[215.  102.7]
[ 78.4 102.7  98.5  75.2]
188.0


############################  NumPy: Basic Statistics

In [5]:
#STANDARD DEVIATION
#Correlation coefficients.

#MEAN
# Print out the mean of np_height_in
print(np_weight_lb.mean())

#MEDIAN
# Print out the median of np_height_in
print(np.median(np_weight_lb))



# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))


88.7
88.45
Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]
